[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "edss-backend"
version = "0.1.0"
description = "Backend of the web application"
authors = [
    { name = "stefanlight8", email = "64615032+stefanlight8@users.noreply.github.com" }
]
license = { file = "LICENSE" }
requires-python = ">=3.13"
dependencies = [
    "edss-journal",
    "msgspec>=0.19.0",
    "sanic>=25.3.0",
]

[project.scripts]
serve = "edss_backend:serve"

[tool.uv.sources]
edss-journal = { workspace = true }
