[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "edss-backend"
version = "0.1.0"
description = "Backend of the web application"
authors = [
    { name = "stefanlight8", email = "64615032+stefanlight8@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "msgspec>=0.19.0",
    "sanic>=25.3.0",
]

[project.scripts]
edss-backend = "edss_backend:main"
